# .travis.yml
#
# This source file is part of the SDGKeyboardDesign open source project.
#
# Copyright ©2019 Jeremy David Giesbrecht.
#
# Soli Deo gloria.
#
# This software is subject to copyright law.
# It may not be used, copied, distributed or modified without first obtaining a private licence from the copyright holder(s).

language: generic
matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job macos"
    - name: "Linux"
      os: linux
      dist: bionic
      script:
        - "export SWIFT_VERSION=5.1.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job linux"
    - name: "iOS"
      os: osx
      osx_image: xcode11.2
      language: objective-c
      xcode_sdk: iphonesimulator
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job ios"
    - name: "watchOS"
      os: osx
      osx_image: xcode11.2
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job watchos"
    - name: "tvOS"
      os: osx
      osx_image: xcode11.2
      language: objective-c
      xcode_sdk: appletvsimulator
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job tvos"
    - name: "Miscellaneous"
      os: linux
      dist: bionic
      script:
        - "export SWIFT_VERSION=5.1.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job miscellaneous"
    - name: "Deployment"
      os: linux
      env:
        - secure: "kTO6df9ImOWf3/rcPtdZK985e9B9Q5YFWVtvWuwpEMXW4HOoHapb9XigFoaFEBa+4zPhrUrKYk4+BJvVEAOTKEQ/bF/M+ZPfh5A2ruE6L2cwdrKH+hpUx+4wgR4d21d5wyL/Nbv1tfPIJ2xkgm+CfUAnWpWLHP5fghBQ4WoTtBQHLZBfM/ILdwnpV/nhP9oXyRZn8J2cnpGoqUkh3eZKCrjeZyDBYLNTGFb6f3nHNWD3ANvBXZyJs9UpeF69tNttKFaGIYgU3MdH9pyyI0pglhX7s15FTlOljwxypzqDprX+RamSrFHXKc7MVMUGGB4GWwJ7uFFKxLyA9zlbMaVOvsYMJkgEZq0JXODeBv9aFKjGQC64lc6M8eRYCbD9rd2jI2H3U5KLHSFPTg+VXQzV6ANlM5Jkwb5RSTQS0JAldC5agEdsEJ432C9gmreqZEPnS8qjuPrzFzis/Jf5oiMFUJIWP0jWRmKbgWQyWeXYRzBgYzqCthHM8ySXlU3vVR3FTZOi4BuYVOv6B/lJ71axIUCSmD5OCp3F4Z53K6vGAw3Qry1sX5lPPKEiLsjiqTvmLYPKgcrgR/QhMReXhxsTBx6WMrLVjFzTUsSbV+GasOoMcpySfXGq+mag3ukIztOhJxN2pVZNB4ooBZySrv74ydsr8FEd+VH8xtW5xB8b+SM="
      if: branch = master and (not type = pull_request)

      deploy:
        provider: pages
        local_dir: docs
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
      dist: bionic
      script:
        - "export SWIFT_VERSION=5.1.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job deployment"

cache:
  directories:
  - $HOME/Library/Caches/ca.solideogloria.Workspace
  - $HOME/.cache/ca.solideogloria.Workspace
